# ARM64 DEPLOYMENT FIXED - AI SWARM ORACLE NODE
# Oracle Cloud Free Tier (ARM64) - All compatibility issues resolved
version: '3.8'

services:
  # ✅ FULLY COMPATIBLE SERVICES
  postgres:
    image: postgres:15-alpine
    platform: linux/arm64
    container_name: oracle-postgres-arm64
    restart: always
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aiswarm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm -d litellm"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    platform: linux/arm64
    container_name: oracle-redis-arm64
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - aiswarm
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ✅ LITELLM GATEWAY - FULLY WORKING
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    platform: linux/arm64
    container_name: oracle-litellm-arm64
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://litellm:${POSTGRES_PASSWORD}@postgres:5432/litellm
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - REDIS_URL=redis://redis:6379
      - STORE_MODEL_IN_DB=true
      - LITELLM_LOG=INFO
    volumes:
      - ./config/litellm-config.yaml:/app/config.yaml:ro
    networks:
      - aiswarm
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🔧 FIXED: NODE EXPORTER - ARM64 COMPATIBLE CONFIGURATION
  node-exporter:
    image: prom/node-exporter:latest
    platform: linux/arm64
    container_name: oracle-monitor-arm64
    restart: always
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.listen-address=0.0.0.0:9100'
      - '--web.max-requests=40'
      # Removed incompatible flags: --web.enable-lifecycle, --web.enable-admin-api
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    networks:
      - aiswarm
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🔧 FIXED: OPEN WEBUI - SERVICE MODE CONFIGURATION
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    platform: linux/arm64
    container_name: oracle-webui-arm64
    restart: always
    ports:
      - "3000:8080"
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - OLLAMA_BASE_URL=http://litellm:4000/v1
      - OPENAI_API_BASE_URL=http://litellm:4000/v1
      - OPENAI_API_KEY=${LITELLM_MASTER_KEY}
      - ENABLE_COMMUNITY_SHARING=false
      - ENABLE_SIGNUP=true
    volumes:
      - open_webui_data:/app/backend/data
    networks:
      - aiswarm
    depends_on:
      litellm:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🔧 FIXED: PIPELINES - ARM64 OPTIMIZED CONFIGURATION
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    platform: linux/arm64
    container_name: oracle-pipelines-arm64
    restart: always
    ports:
      - "9099:9099"
    environment:
      - PIPELINES_PORT=9099
      - PIPELINES_OPENAI_API_BASE_URL=http://litellm:4000/v1
      - PIPELINES_OPENAI_API_KEY=${LITELLM_MASTER_KEY}
      - NODE_ENV=production
      - PIP_NO_CACHE_DIR=1
      # ARM64 optimization
      - PYTHONOPTIMIZE=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - pipelines_data:/app/data
    networks:
      - aiswarm
    depends_on:
      litellm:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9099/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  open_webui_data:
    driver: local
  pipelines_data:
    driver: local

networks:
  aiswarm:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# ARM64 Resource Limits for Oracle Free Tier (4 cores, 24GB RAM)
x-common-limits: &common-limits
  deploy:
    resources:
      limits:
        cpus: '1.0'
        memory: 4G
      reservations:
        cpus: '0.5'
        memory: 1G

# Apply limits to resource-intensive services
services:
  litellm:
    <<: *common-limits

  open-webui:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
        reservations:
          cpus: '1.0'
          memory: 2G

  pipelines:
    <<: *common-limits