groups:
- name: gpu_alerts
  rules:
  - alert: HighGPUUtilization
    expr: gpu_utilization > 0.85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High GPU utilization on Starlord"
      description: "GPU utilization is {{ $value }}% for more than 5 minutes."

  - alert: HighTemperature
    expr: gpu_temperature > 80
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High GPU temperature on Starlord"
      description: "GPU temperature is {{ $value }}°C."

- name: latency_alerts
  rules:
  - alert: HighRequestLatency
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High request latency"
      description: "95th percentile latency is {{ $value }}s."

- name: cost_alerts
  rules:
  - alert: HighCostOverrun
    expr: rate(api_cost_total[1h]) > 20
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Cost overrun detected"
      description: "API cost rate is {{ $value }} USD/hour, over 20% threshold."