general_settings:
  master_key: sk-local-only

litellm_settings:
  cache: true
  cache_params:
    type: redis
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  max_budget: 25
  budget_duration: 30d

router_settings:
  routing_strategy: rate_limit_aware_v2
  context_window_fallbacks:
    - match: "context_window_exceeded"
      to_model: google/gemini-2.5-flash

model_list:
  - model_name: google/gemini-2.5-pro
    litellm_params: { model: "gemini-2.5-pro", api_key: "os.environ/GOOGLE_API_KEY_1" }
  - model_name: google/gemini-2.5-flash
    litellm_params: { model: "gemini-2.5-flash", api_key: "os.environ/GOOGLE_API_KEY_2" }
  - model_name: google/gemini-embedding-001
    litellm_params: { model: "gemini-embedding-001", api_key: "os.environ/GOOGLE_API_KEY_2" }

budgets:
  providers:
    google: { max_budget: 20, budget_duration: 30d }
  models:
    google/gemini-2.5-pro: { max_budget: 10, budget_duration: 30d }
    google/gemini-2.5-flash: { max_budget: 12, budget_duration: 30d }
  tags:
    roleplay: { max_budget: 3, budget_duration: 7d }